import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {


  return (
    <div className="h-screen bg-primary">
      <Head>
        <title>Polling-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid place-content-center h-screen grid gap-4 text-center'>
        <h1 className='text-chalk font-semibold text-6xl'>A Simple Polling App</h1>
        <h1 className='text-gray-400 text-lg text-center'>inspired by <span className='underline'><a target="_blank" href='https://rallly.co/'>rallly.co</a></span></h1>
        <h1 className='text-chalk font-semibold text-4xl mx-4'>Let's make a poll. Click on create.</h1>
        <a href='/new' className='bg-black text-white rounded-full w-40 mx-auto px-10 py-4 mt-10 font-semibold text-2xl'>Create</a>
        <h1 className='text-gray-400 text-lg text-center'>[Engineered with Nest.js, Next.js, Prisma, PostgreSQL, Docker]</h1>
      </main>

      
    </div>
  )
}

export default Home
